# Site settings
title: "PixelNewt Studio"
email: "dereknutile@gmail.com"
description: "Website & application development and delivery"
tagline: "Not another <del>agency</del>"
baseurl: "/"
url: "http://pixelnewt.com/"
baseuser: "pixelnewt"

# Build settings
markdown: kramdown
permalink: pretty
