# company settings
title: "PixelNewt"
company: "Pixelnewt LLC"
address: "Oregon, USA"
phone-string: "503-657-1842"
phone-number: "+15036571842"

# constant copy
description: "Crafters of websites, web applications, and software services located in Oregon, USA."
mission: "Create Attractive, Focused, Robust, and Secure Web Applications that we Brag About"
mos: "We Measure Success by Growing Your Internet Business"
summary: "Engineers of Awesome Web Applications and Software Services"
tagline: "We Make Beautiful, Robust, Applications for Web & Mobile"

# meta data
meta_content: "Crafters of websites, web applications, and software services located in Oregon, USA."
meta_tagline: "Our Focus is Building Your Internet"

# urls
baseurl: "" # no trailing slash
url: "http://pixelnewt.com/"
urlNoSlash: "http://pixelnewt.com"

# miscellaneous
baseuser: "pixelnewt"
gacode: "UA-53524614-1"

# Build settings
markdown: kramdown
permalink: pretty
