# Site settings
title: "PixelNewt"
company: "Pixelnewt LLC"
description: "Crafters of websites, web applications, and software services located in Oregon, USA."
mission: "Create Attractive, Focused, Robust, and Secure Web Applications that we Brag About"
mos: "We Measure Success by Growing Your Internet Business"
summary: "Engineers of Awesome Web Applications and Software Services"
tagline: "We Make Beautiful, Robust, Applications for Web & Mobile"
baseurl: "" # no trailing slash
url: "http://pixelnewt.com/"
urlNoSlash: "http://pixelnewt.com"
baseuser: "pixelnewt"
address: "Oregon, USA"
gacode: "UA-53524614-1"

# Build settings
markdown: kramdown
permalink: pretty

meta_content: "Crafters of websites, web applications, and software services located in Oregon, USA."
meta_tagline: "Our Focus is Building Your Internet"
