# Site settings
title: "PixelNewt"
email: "dereknutile@gmail.com"
description: "Crafters of practical web applications and services"
tagline: "Not another <del>agency</del>"
baseurl: "/"
url: "http://pixelnewt.com/"
urlNoSlash: "http://pixelnewt.com"
baseuser: "pixelnewt"
logosvg: "/assets/img/nav-logo.png"
address: "Oregon, USA"

# Build settings
markdown: kramdown
permalink: pretty